# Generated by Django 6.0.2 on 2026-02-26 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_akademik', models.CharField(max_length=10)),
                ('daya_tampung', models.IntegerField(default=0)),
                ('pendaftar', models.IntegerField(default=0)),
                ('lulus_seleksi', models.IntegerField(default=0)),
                ('mhs_baru_reguler', models.IntegerField(default=0)),
                ('mhs_aktif_reguler', models.IntegerField(default=0)),
                ('mhs_baru_transfer', models.IntegerField(default=0)),
                ('mhs_aktif_transfer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PenelitianDTPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber_pembiayaan', models.CharField(choices=[('Mandiri', 'Mandiri'), ('PT', 'Perguruan Tinggi'), ('Nasional', 'Nasional'), ('Internasional', 'Internasional')], max_length=100)),
                ('ts_2', models.IntegerField(default=0)),
                ('ts_1', models.IntegerField(default=0)),
                ('ts', models.IntegerField(default=0)),
                ('jumlah', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prodi', models.CharField(max_length=100)),
                ('fakultas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PublikasiMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_publikasi', models.CharField(max_length=200)),
                ('ts_2', models.IntegerField(default=0)),
                ('ts_1', models.IntegerField(default=0)),
                ('ts', models.IntegerField(default=0)),
                ('jumlah', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SumberPendanaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber', models.CharField(max_length=200)),
                ('ts_2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ts_1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('jumlah', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
                ('link_bukti', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel1Kerjasama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lembaga_mitra', models.CharField(max_length=255)),
                ('tingkat', models.CharField(max_length=50)),
                ('judul_kegiatan', models.TextField()),
                ('manfaat', models.TextField()),
                ('durasi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TenagaKependidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_tenaga', models.CharField(max_length=100)),
                ('jenjang_s3', models.IntegerField(default=0)),
                ('jenjang_s2', models.IntegerField(default=0)),
                ('jenjang_s1', models.IntegerField(default=0)),
                ('unit_kerja', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IdentitasPengusul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perguruan_tinggi', models.CharField(default='Universitas Pradita', max_length=200)),
                ('unit_pengelola', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_program', models.CharField(default='Magister', max_length=100)),
                ('kota_pendirian', models.CharField(default='Tangerang', max_length=100)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('nomor_telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('email_website', models.CharField(blank=True, max_length=200, null=True)),
                ('nomor_sk_pendirian', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_sk_pendirian', models.DateField(blank=True, null=True)),
                ('pejabat_sk_pendirian', models.CharField(blank=True, max_length=100, null=True)),
                ('nomor_sk_pembukaan', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_sk_pembukaan', models.DateField(blank=True, null=True)),
                ('pejabat_sk_pembukaan', models.CharField(blank=True, max_length=100, null=True)),
                ('tahun_pertama_menerima', models.IntegerField(blank=True, null=True)),
                ('peringkat_akreditasi', models.CharField(blank=True, max_length=50, null=True)),
                ('nomor_sk_ban_pt', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_program_studi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.programstudi')),
            ],
        ),
    ]
