# Generated by Django 6.0.2 on 2026-02-22 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prodi', models.CharField(max_length=100)),
                ('fakultas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IdentitasPengusul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perguruan_tinggi', models.CharField(max_length=200)),
                ('unit_pengelola', models.CharField(max_length=200)),
                ('jenis_program', models.CharField(default='Magister', max_length=100)),
                ('alamat', models.TextField()),
                ('nomor_telepon', models.CharField(max_length=50)),
                ('email_website', models.CharField(max_length=200)),
                ('nomor_sk_pendirian', models.CharField(max_length=100)),
                ('tanggal_sk_pendirian', models.DateField()),
                ('pejabat_sk_pendirian', models.CharField(max_length=100)),
                ('nomor_sk_pembukaan', models.CharField(max_length=100)),
                ('tanggal_sk_pembukaan', models.DateField()),
                ('pejabat_sk_pembukaan', models.CharField(max_length=100)),
                ('tahun_pertama_menerima', models.IntegerField()),
                ('peringkat_akreditasi', models.CharField(max_length=50)),
                ('nomor_sk_ban_pt', models.CharField(max_length=100)),
                ('nama_program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programstudi')),
            ],
        ),
    ]
