# Generated by Django 6.0.2 on 2026-03-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_akademik', models.CharField(max_length=10)),
                ('daya_tampung', models.IntegerField(default=0)),
                ('pendaftar', models.IntegerField(default=0)),
                ('lulus_seleksi', models.IntegerField(default=0)),
                ('mhs_baru_reguler', models.IntegerField(default=0)),
                ('mhs_baru_transfer', models.IntegerField(default=0)),
                ('mhs_aktif_reguler', models.IntegerField(default=0)),
                ('mhs_aktif_transfer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DosenTetap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dosen', models.CharField(max_length=255)),
                ('nidk', models.CharField(max_length=50)),
                ('magister', models.CharField(blank=True, max_length=255, null=True)),
                ('doktor', models.CharField(blank=True, max_length=255, null=True)),
                ('bidang_keahlian', models.CharField(max_length=255)),
                ('jabatan_akademik', models.CharField(choices=[('Tenaga Pengajar', 'Tenaga Pengajar'), ('Asisten Ahli', 'Asisten Ahli'), ('Lektor', 'Lektor'), ('Lektor Kepala', 'Lektor Kepala'), ('Guru Besar', 'Guru Besar')], max_length=100)),
                ('sertifikat_pendidik', models.CharField(blank=True, max_length=255, null=True)),
                ('matkul_diampu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IdentitasPengusul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perguruan_tinggi', models.CharField(default='Universitas Pradita', max_length=200)),
                ('unit_pengelola', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_program', models.CharField(default='Sarjana', max_length=100)),
                ('program_studi', models.CharField(blank=True, max_length=100, null=True)),
                ('kota_pendirian', models.CharField(default='Tangerang', max_length=100)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('nomor_sk_pendirian', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_sk_pendirian', models.DateField(blank=True, null=True)),
                ('pejabat_sk_pendirian', models.CharField(blank=True, max_length=100, null=True)),
                ('tahun_pertama_menerima', models.IntegerField(blank=True, null=True)),
                ('peringkat_akreditasi', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kurikulum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=1)),
                ('kode_matkul', models.CharField(max_length=20)),
                ('nama_matkul', models.CharField(max_length=255)),
                ('matkul_kompetensi', models.BooleanField(default=False)),
                ('sks_kuliah', models.IntegerField(default=0)),
                ('sks_seminar', models.IntegerField(default=0)),
                ('sks_praktikum', models.IntegerField(default=0)),
                ('jam_kredit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('capaian_sikap', models.BooleanField(default=False)),
                ('capaian_pengetahuan', models.BooleanField(default=False)),
                ('capaian_keterampilan_umum', models.BooleanField(default=False)),
                ('capaian_keterampilan_khusus', models.BooleanField(default=False)),
                ('dokumen_rencana_pembelajaran', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_penyelenggara', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PenelitianDTPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber_pembiayaan', models.CharField(choices=[('Mandiri', 'Mandiri'), ('PT', 'Perguruan Tinggi'), ('Nasional', 'Nasional'), ('Internasional', 'Internasional')], max_length=100)),
                ('ts_2', models.IntegerField(default=0)),
                ('ts_1', models.IntegerField(default=0)),
                ('ts', models.IntegerField(default=0)),
                ('jumlah', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PenggunaanDana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_penggunaan', models.CharField(max_length=255)),
                ('ts_2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ts_1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rata_rata', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prodi', models.CharField(max_length=100)),
                ('fakultas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PublikasiMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_publikasi', models.CharField(max_length=200)),
                ('ts_2', models.IntegerField(default=0)),
                ('ts_1', models.IntegerField(default=0)),
                ('ts', models.IntegerField(default=0)),
                ('jumlah', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SistemTataKelola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SumberPendanaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber', models.CharField(max_length=200)),
                ('ts_2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ts_1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('jumlah', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
                ('link_bukti', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel1Kerjasama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lembaga_mitra', models.CharField(max_length=255)),
                ('tingkat', models.CharField(max_length=50)),
                ('judul_kegiatan', models.TextField()),
                ('manfaat', models.TextField()),
                ('durasi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel_5_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_sarana_prasarana', models.CharField(max_length=255)),
                ('jumlah_unit', models.IntegerField(default=0)),
                ('total_luas_m2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('kepemilikan', models.CharField(choices=[('Milik Sendiri', 'Milik Sendiri'), ('Sewa', 'Sewa'), ('Kerjasama', 'Kerjasama')], default='Milik Sendiri', max_length=100)),
                ('kondisi', models.CharField(choices=[('Terawat', 'Terawat'), ('Tidak Terawat', 'Tidak Terawat')], default='Terawat', max_length=100)),
                ('unit_pengelola', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenagaKependidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_tenaga', models.CharField(max_length=100)),
                ('jenjang_s3', models.IntegerField(default=0)),
                ('jenjang_s2', models.IntegerField(default=0)),
                ('jenjang_s1', models.IntegerField(default=0)),
                ('unit_kerja', models.CharField(max_length=100)),
            ],
        ),
    ]
