# Generated by Django 6.0.2 on 2026-02-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosenTetap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dosen', models.CharField(max_length=255)),
                ('nidn', models.CharField(max_length=50)),
                ('magister', models.CharField(blank=True, max_length=255, null=True)),
                ('doktor', models.CharField(blank=True, max_length=255, null=True)),
                ('bidang_keahlian', models.CharField(max_length=255)),
                ('jabatan_akademik', models.CharField(choices=[('Tenaga Pengajar', 'Tenaga Pengajar'), ('Asisten Ahli', 'Asisten Ahli'), ('Lektor', 'Lektor'), ('Lektor Kepala', 'Lektor Kepala'), ('Guru Besar', 'Guru Besar')], max_length=100)),
                ('sertifikat_pendidik', models.CharField(blank=True, max_length=255, null=True)),
                ('matkul_diampu', models.TextField()),
            ],
        ),
    ]
