# Generated by Django 6.0.2 on 2026-02-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_akademik', models.CharField(max_length=10)),
                ('daya_tampung', models.IntegerField()),
                ('pendaftar', models.IntegerField()),
                ('lulus_seleksi', models.IntegerField()),
                ('mhs_baru_reguler', models.IntegerField()),
                ('mhs_aktif_reguler', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SumberPendanaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber', models.CharField(max_length=200)),
                ('ts_2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ts_1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('link_bukti', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenagaKependidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_tenaga', models.CharField(max_length=100)),
                ('jenjang_s3', models.IntegerField(default=0)),
                ('jenjang_s2', models.IntegerField(default=0)),
                ('jenjang_s1', models.IntegerField(default=0)),
                ('unit_kerja', models.CharField(max_length=100)),
            ],
        ),
    ]
