# Generated by Django 6.0.2 on 2026-02-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dosentetap'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenggunaanDana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_penggunaan', models.CharField(max_length=255)),
                ('ts_2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ts_1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rata_rata', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
