# Generated by Django 6.0.2 on 2026-02-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_penggunaandana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurikulum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=1)),
                ('kode_matkul', models.CharField(max_length=20)),
                ('nama_matkul', models.CharField(max_length=255)),
                ('matkul_kompetensi', models.BooleanField(default=False)),
                ('sks_kuliah', models.IntegerField(default=0)),
                ('sks_seminar', models.IntegerField(default=0)),
                ('sks_praktikum', models.IntegerField(default=0)),
                ('jam_kredit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('capaian_sikap', models.BooleanField(default=False)),
                ('capaian_pengetahuan', models.BooleanField(default=False)),
                ('capaian_keterampilan_umum', models.BooleanField(default=False)),
                ('capaian_keterampilan_khusus', models.BooleanField(default=False)),
                ('dokumen_rencana_pembelajaran', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_penyelenggara', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='dosentetap',
            old_name='nidn',
            new_name='nidk',
        ),
    ]
