# Generated by Django 6.0.2 on 2026-02-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_kurikulum_rename_nidn_dosentetap_nidk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identitaspengusul',
            old_name='nomor_sk_ban_pt',
            new_name='program_studi',
        ),
        migrations.RenameField(
            model_name='identitaspengusul',
            old_name='nomor_telepon',
            new_name='telepon',
        ),
        migrations.RenameField(
            model_name='identitaspengusul',
            old_name='email_website',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='programstudi',
            old_name='fakultas',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='identitaspengusul',
            name='nama_program_studi',
        ),
        migrations.RemoveField(
            model_name='identitaspengusul',
            name='nomor_sk_pembukaan',
        ),
        migrations.RemoveField(
            model_name='identitaspengusul',
            name='pejabat_sk_pembukaan',
        ),
        migrations.RemoveField(
            model_name='identitaspengusul',
            name='tanggal_sk_pembukaan',
        ),
        migrations.RemoveField(
            model_name='programstudi',
            name='nama_prodi',
        ),
        migrations.AddField(
            model_name='identitaspengusul',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='identitaspengusul',
            name='jenis_program',
            field=models.CharField(default='Sarjana', max_length=100),
        ),
    ]
