# Generated by Django 6.0.2 on 2026-02-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_nomor_sk_ban_pt_identitaspengusul_program_studi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemTataKelola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_tata_kelola', models.CharField(choices=[('Pendidikan', 'Pendidikan'), ('Keuangan', 'Keuangan'), ('SDM', 'SDM'), ('Sarana Prasarana', 'Sarana Prasarana'), ('Lainnya', 'Lainnya')], max_length=100)),
                ('nama_sistem', models.CharField(max_length=255)),
                ('akses', models.CharField(choices=[('Internet', 'Internet'), ('Lokal', 'Lokal')], max_length=50)),
                ('unit_pengelola', models.CharField(max_length=255)),
            ],
        ),
    ]
