# Generated by Django 6.0.3 on 2026-03-09 04:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prodi', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Master Program Studi',
            },
        ),
        migrations.CreateModel(
            name='Tabel_1A1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_kerja', models.CharField(max_length=255)),
                ('nama_ketua', models.CharField(max_length=255)),
                ('periode_jabatan', models.CharField(max_length=100)),
                ('pendidikan_terakhir', models.CharField(max_length=50)),
                ('jabatan_fungsional', models.CharField(max_length=100)),
                ('tupoksi', models.TextField()),
            ],
            options={
                'verbose_name': 'Tabel 1.A.1 Pimpinan & Tupoksi',
            },
        ),
        migrations.CreateModel(
            name='IdentitasPengusul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_resmi', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_pengelola', models.CharField(help_text='Nama Fakultas/Sekolah Tinggi', max_length=200)),
                ('perguruan_tinggi', models.CharField(default='Universitas Pradita', max_length=200)),
                ('kota_pendirian', models.CharField(default='Tangerang', max_length=100)),
                ('tanggal_dokumen', models.DateField(default=django.utils.timezone.now)),
                ('program_studi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identitas_pengusul', to='lkps_app.programstudi')),
            ],
            options={
                'verbose_name_plural': 'Data Identitas Pengusul',
            },
        ),
    ]
