# Generated by Django 6.0.3 on 2026-03-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabel_1A4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dosen', models.CharField(max_length=255)),
                ('sks_ps_sendiri', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sks_ps_lain', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sks_pt_lain', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sks_penelitian', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sks_pkm', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sks_tambahan', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': '1.A.4 Beban Kerja DTPR',
            },
        ),
        migrations.CreateModel(
            name='Tabel_1A5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_tenaga', models.CharField(max_length=255)),
                ('s3', models.IntegerField(default=0)),
                ('s2', models.IntegerField(default=0)),
                ('s1', models.IntegerField(default=0)),
                ('d3', models.IntegerField(default=0)),
                ('d2_d1', models.IntegerField(default=0)),
                ('sma_smk', models.IntegerField(default=0)),
                ('unit_kerja', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '1.A.5 Tenaga Kependidikan',
            },
        ),
        migrations.CreateModel(
            name='Tabel_1A_Dana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber_dana', models.CharField(max_length=255)),
                ('ts_2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ts_1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': '1.A.2 & 1.A.3 Pendanaan',
            },
        ),
        migrations.CreateModel(
            name='Tabel_2A_Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_akademik', models.CharField(max_length=20)),
                ('daya_tampung', models.IntegerField(default=0)),
                ('pendaftar', models.IntegerField(default=0)),
                ('lulus_seleksi', models.IntegerField(default=0)),
                ('mhs_baru_reguler', models.IntegerField(default=0)),
                ('mhs_baru_transfer', models.IntegerField(default=0)),
                ('total_mhs_reguler', models.IntegerField(default=0)),
                ('total_mhs_transfer', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '2.A Data Mahasiswa',
            },
        ),
        migrations.CreateModel(
            name='Tabel_2B_Kurikulum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('kode_matkul', models.CharField(max_length=20)),
                ('nama_matkul', models.CharField(max_length=255)),
                ('bobot_sks', models.IntegerField()),
                ('unit_penyelenggara', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '2.B.1 - 2.B.3 Kurikulum',
            },
        ),
        migrations.CreateModel(
            name='Tabel_2B_Lulusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_lulus', models.CharField(max_length=20)),
                ('jumlah_lulusan', models.IntegerField(default=0)),
                ('rata_ipk', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('masa_studi', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
            options={
                'verbose_name': '2.B.4 - 2.B.6 Lulusan',
            },
        ),
        migrations.CreateModel(
            name='Tabel_3_Penelitian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber_pembiayaan', models.CharField(max_length=255)),
                ('ts_2', models.IntegerField(default=0)),
                ('ts_1', models.IntegerField(default=0)),
                ('ts', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '3 Penelitian DTPR',
            },
        ),
        migrations.CreateModel(
            name='Tabel_4_PkM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber_pembiayaan', models.CharField(max_length=255)),
                ('ts_2', models.IntegerField(default=0)),
                ('ts_1', models.IntegerField(default=0)),
                ('ts', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '4 PkM DTPR',
            },
        ),
        migrations.CreateModel(
            name='Tabel_5_Akuntabilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspek', models.CharField(max_length=255)),
                ('uraian', models.TextField()),
            ],
            options={
                'verbose_name': '5 Akuntabilitas',
            },
        ),
        migrations.CreateModel(
            name='Tabel_6_Misi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visi', models.TextField()),
                ('misi', models.TextField()),
                ('tujuan', models.TextField()),
            ],
            options={
                'verbose_name': '6 Visi Misi Tujuan',
            },
        ),
    ]
