# Generated by Django 6.0.3 on 2026-03-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0002_tabel_1a4_tabel_1a5_tabel_1a_dana_tabel_2a_mahasiswa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabel_1A2_Sumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber_dana', models.CharField(max_length=255)),
                ('ts_2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ts_1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('link_bukti', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel_1A3_Penggunaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penggunaan', models.CharField(max_length=255)),
                ('ts_2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ts_1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('link_bukti', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tabel_1A_Dana',
        ),
    ]
