# Generated by Django 6.0.3 on 2026-03-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0003_tabel_1a2_sumber_tabel_1a3_penggunaan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programstudi',
            options={},
        ),
        migrations.AddField(
            model_name='programstudi',
            name='akreditasi',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programstudi',
            name='jenjang_studi',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programstudi',
            name='no_sk',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
