# Generated by Django 6.0.3 on 2026-03-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0005_profilpengguna'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identitaspengusul',
            options={},
        ),
        migrations.RemoveField(
            model_name='identitaspengusul',
            name='kota_pendirian',
        ),
        migrations.RemoveField(
            model_name='identitaspengusul',
            name='tanggal_dokumen',
        ),
        migrations.AddField(
            model_name='identitaspengusul',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='identitaspengusul',
            name='email_web',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='identitaspengusul',
            name='kota_sampul',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='identitaspengusul',
            name='nama_ps_sampul',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='identitaspengusul',
            name='nama_pt_sampul',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='identitaspengusul',
            name='sk_ps',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='identitaspengusul',
            name='sk_pt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='identitaspengusul',
            name='tahun_sampul',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='identitaspengusul',
            name='telepon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='identitaspengusul',
            name='tgl_sk_ps',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identitaspengusul',
            name='tgl_sk_pt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identitaspengusul',
            name='perguruan_tinggi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='identitaspengusul',
            name='unit_pengelola',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
