# Generated by Django 6.0.3 on 2026-03-16 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0006_alter_identitaspengusul_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimPenyusun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=200)),
                ('nidn', models.CharField(blank=True, max_length=50)),
                ('jabatan', models.CharField(blank=True, max_length=100)),
                ('tanggal_pengisian', models.DateField(blank=True, null=True)),
                ('tanda_tangan', models.FileField(blank=True, null=True, upload_to='ttd_penyusun/')),
                ('identitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tim_penyusun', to='lkps_app.identitaspengusul')),
            ],
            options={
                'verbose_name_plural': 'Tim Penyusun',
            },
        ),
    ]
