# Generated by Django 6.0.3 on 2026-03-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0007_timpenyusun'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitaspengusul',
            name='logo_pt',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='timpenyusun',
            name='tanda_tangan',
            field=models.ImageField(blank=True, null=True, upload_to='ttd_penyusun/'),
        ),
    ]
