# Generated by Django 6.0.3 on 2026-03-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0008_identitaspengusul_logo_pt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabel_2A2_Asal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asal_mahasiswa', models.CharField(max_length=255)),
                ('ts_2', models.IntegerField(default=0)),
                ('ts_1', models.IntegerField(default=0)),
                ('ts', models.IntegerField(default=0)),
                ('link_bukti', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '2.A.2 Keragaman Asal',
            },
        ),
        migrations.CreateModel(
            name='Tabel_2A3_Kondisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('ts_2', models.IntegerField(default=0)),
                ('ts_1', models.IntegerField(default=0)),
                ('ts', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '2.A.3 Kondisi Jumlah',
            },
        ),
    ]
