# Generated by Django 6.0.3 on 2026-03-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0009_tabel_2a2_asal_tabel_2a3_kondisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabel_2B1_MK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mk', models.CharField(max_length=255)),
                ('sks', models.IntegerField(default=0)),
                ('semester', models.IntegerField(default=0)),
                ('pl1', models.BooleanField(default=False)),
                ('pl2', models.BooleanField(default=False)),
                ('pl3', models.BooleanField(default=False)),
                ('pl4', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel_2B2_CPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_cpl', models.CharField(max_length=100)),
                ('pl1', models.BooleanField(default=False)),
                ('pl2', models.BooleanField(default=False)),
                ('pl3', models.BooleanField(default=False)),
                ('pl4', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel_2B3_Pemenuhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpl', models.CharField(max_length=100)),
                ('cpmk', models.CharField(max_length=100)),
                ('smt1', models.CharField(blank=True, max_length=100)),
                ('smt2', models.CharField(blank=True, max_length=100)),
                ('smt3', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Tabel_2B_Kurikulum',
        ),
    ]
