# Generated by Django 6.0.3 on 2026-03-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0010_tabel_2b1_mk_tabel_2b2_cpl_tabel_2b3_pemenuhan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabel_2B4_MasaTunggu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_lulus', models.CharField(max_length=20)),
                ('jml_lulusan', models.IntegerField(default=0)),
                ('jml_terlacak', models.IntegerField(default=0)),
                ('waktu_tunggu', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel_2B5_BidangKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_lulus', models.CharField(max_length=20)),
                ('jml_lulusan', models.IntegerField(default=0)),
                ('jml_terlacak', models.IntegerField(default=0)),
                ('bidang_infokom', models.IntegerField(default=0)),
                ('bidang_non_infokom', models.IntegerField(default=0)),
                ('tingkat_multinasional', models.IntegerField(default=0)),
                ('tingkat_nasional', models.IntegerField(default=0)),
                ('tingkat_wirausaha', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel_2B6_Kepuasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kemampuan', models.CharField(max_length=255)),
                ('sangat_baik', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('baik', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('cukup', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('kurang', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('tindak_lanjut', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel_2B_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_alumni_3thn', models.IntegerField(default=0)),
                ('total_responden', models.IntegerField(default=0)),
                ('total_mhs_aktif_ts', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Tabel_2B_Lulusan',
        ),
    ]
