# Generated by Django 6.0.3 on 2026-03-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0011_tabel_2b4_masatunggu_tabel_2b5_bidangkerja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabel_3_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_roadmap', models.URLField(blank=True, null=True)),
                ('total_jenis_hibah', models.IntegerField(default=0)),
                ('total_mitra', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel_3A1_Sarana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prasarana', models.CharField(max_length=255)),
                ('daya_tampung', models.IntegerField(default=0)),
                ('luas_ruang', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kepemilikan', models.CharField(max_length=50)),
                ('lisensi', models.CharField(max_length=50)),
                ('perangkat', models.TextField(blank=True, null=True)),
                ('link_bukti', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel_3A2_Penelitian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dtpr', models.CharField(max_length=255)),
                ('jml_mhs', models.IntegerField(default=0)),
                ('judul', models.TextField()),
                ('jenis_hibah', models.CharField(max_length=255)),
                ('sumber_lni', models.CharField(max_length=10)),
                ('durasi', models.DecimalField(decimal_places=1, default=1, max_digits=5)),
                ('dana_ts2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dana_ts1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dana_ts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('link_bukti', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel_3C1_Kerjasama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField()),
                ('mitra', models.CharField(max_length=255)),
                ('sumber_lni', models.CharField(max_length=10)),
                ('durasi', models.DecimalField(decimal_places=1, default=1, max_digits=5)),
                ('dana_ts2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dana_ts1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dana_ts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('link_bukti', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel_3C2_Publikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dtpr', models.CharField(max_length=255)),
                ('judul', models.TextField()),
                ('jenis_pub', models.CharField(max_length=50)),
                ('ts2', models.BooleanField(default=False)),
                ('ts1', models.BooleanField(default=False)),
                ('ts', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel_3C3_HKI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField()),
                ('jenis_hki', models.CharField(max_length=255)),
                ('nama_dtpr', models.CharField(max_length=255)),
                ('ts2', models.BooleanField(default=False)),
                ('ts1', models.BooleanField(default=False)),
                ('ts', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Tabel_3_Penelitian',
        ),
    ]
