# Generated by Django 6.0.3 on 2026-03-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0013_tabel_4_summary_tabel_4a1_sarana_tabel_4a2_pkm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabel_5_1_TataKelola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_tata_kelola', models.CharField(max_length=255)),
                ('nama_sistem', models.CharField(blank=True, max_length=255, null=True)),
                ('akses', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_pengelola', models.CharField(blank=True, max_length=255, null=True)),
                ('link_bukti', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel_5_2_Sarana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prasarana', models.CharField(max_length=255)),
                ('daya_tampung', models.IntegerField(default=0)),
                ('luas_ruang', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kepemilikan', models.CharField(max_length=50)),
                ('lisensi', models.CharField(max_length=50)),
                ('perangkat', models.TextField(blank=True, null=True)),
                ('link_bukti', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tabel_5_Akuntabilitas',
        ),
        migrations.AlterModelOptions(
            name='tabel_6_misi',
            options={},
        ),
        migrations.RemoveField(
            model_name='tabel_6_misi',
            name='misi',
        ),
        migrations.RemoveField(
            model_name='tabel_6_misi',
            name='tujuan',
        ),
        migrations.RemoveField(
            model_name='tabel_6_misi',
            name='visi',
        ),
        migrations.AddField(
            model_name='tabel_6_misi',
            name='misi_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tabel_6_misi',
            name='misi_upps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tabel_6_misi',
            name='visi_ps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tabel_6_misi',
            name='visi_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tabel_6_misi',
            name='visi_upps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
